name: Publish SDK to Packagist

on:
  workflow_dispatch:  # 允许手动触发
    inputs:
      version:
        description: 'SDK 版本号 (格式: x.y.z)'
        required: true
        type: string
      force:
        description: '是否强制覆盖分支'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version in composer.json
        if: ${{ inputs.version != '' }}
        run: |
          cd wemeetopenapi
          jq ".version = \"${{ inputs.version }}\"" composer.json > tmp.json && mv tmp.json composer.json
          git config --global user.name "hzh595395786"
          git config --global user.email "595395786@qq.com"
          git add composer.json
          git commit -m "chore: bump version to ${{ inputs.version }}"
          git push origin main

      - name: Split subdirectory to release branch
        run: |
          git subtree split -P wemeetopenapi -b packagist-release
          git push -f origin packagist-release

      - name: Trigger Packagist update
        uses: mheap/update-packagist@v1
        with:
          packagist-token: ${{ secrets.PACKAGIST_TOKEN }}