name: Publish SDK to Packagist

on:
  push:
    tags:
      - 'v*'  # 匹配 v1.0.0 格式的标签
  workflow_dispatch:  # 保留手动触发
    inputs:
      version:
        description: 'SDK 版本号 (格式: x.y.z)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # 自动识别Tag或分支

      - name: Auto-detect version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: tag_version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          echo "version=${TAG_VERSION#v}" >> $GITHUB_OUTPUT  # 去掉v前缀

      - name: Set version (manual trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Update version in composer.json
        run: |
          cd wemeetopenapi
          VERSION="${{ steps.tag_version.outputs.version || env.version }}"
          jq ".version = \"$VERSION\"" composer.json > tmp.json && mv tmp.json composer.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add composer.json
          git commit -m "chore: bump version to $VERSION"
          git push origin main

      - name: Split subdirectory to release branch
        run: |
          git subtree split -P wemeetopenapi -b packagist-release
          git push -f origin packagist-release

      - name: Trigger Packagist update
        uses: mheap/update-packagist@v1
        with:
          packagist-token: ${{ secrets.PACKAGIST_TOKEN }}