name: Manual Publish SDK

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PACKAGIST_TOKEN }}  # 关键修改！使用PAT而非默认Token

      - name: Prepare release branch
        run: |
          # 配置Git身份
          git config --global user.name "hzh595395786"
          git config --global user.email "595395786sh"
          
          # 创建或重置分支
          git checkout --orphan packagist-release
          git rm -rf .
          git checkout main -- wemeetopenapi/
          mv wemeetopenapi/* .
          
          # 提交并推送
          git add .
          git commit -m "Release $(jq -r '.version' composer.json)"
          git push -f origin packagist-release --force-with-lease