name: Publish SDK from Main Branch

on:
  push:
    branches: [ main ]  # 监听main分支的推送
    paths: [ 'wemeetopenapi/composer.json' ]  # 仅当composer.json变更时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from composer.json
        id: get_version
        run: |
          cd wemeetopenapi
          VERSION=$(jq -r '.version' composer.json)
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format in composer.json: $VERSION"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Create packagist release branch
        run: |
          git subtree split -P wemeetopenapi -b packagist-release
          git push -f origin packagist-release

      - name: Notify Packagist
        uses: php-actions/packagist-update@v1
        with:
          packagist-token: ${{ secrets.PACKAGIST_TOKEN }}
          repository-url: https://github.com/${{ github.repository }}